<?php
$string['install']="Installazione";
$string['lang_select']="Selezionare la ligua:";
$string['license']="<b>Condizioni di licenza</b>";
$string['license_ok']="ACCETTO";
$string['license_no']="NON ACCETTO";
$string['license_agree']="<b>Procedendo accetti tutte queste condizioni di licenza</b>";
$string['next']="Prosegui >>>";
$string['end']=">> Fine <<";
$string['step_1_1']="Verranno ora create le tabelle necessarie all'utilizzo dello script.";
$string['step_1_2']="AZZERA TABELLE";
$string['step_1_3']="<b>ATTENZIONE</b>: se le tabelle fossero già presenti nel database esse verranno <b>cancellate</b> e <b>ricreate</b>.";
$string['step_3_1']="Scegliere una password :";
$string['step_3_2']="Reinserire la password :";
$string['step_4_1']="<b>ATTENZIONE</b>: Ricordarsi di cancellare il file <b>setup.php</b> e la cartella <b>setup_files</b>.";
$string['step_4_2']="<b>NOTA</b>: Nelle pagine HTML da monitorare inserire il codice:";
$string['step_4_3']="<b>NOTA</b>: Nelle pagine PHP da monitorare inserire il codice:";
$string['step_4_4']="In caso di problemi utilizzare l'apposito <a href=\"http://www.php-stats.com/forum/\" target=\"_blank\">forum di discussione</a>.";
$string['box_title']="Attenzione:";
$string['done']="Operazione riuscita.";
// ERROR HANDLING
$error['error_updating']="<b>ATTENZIONE: ERRORE CRITICO</b><br><br>Si consiglia di prendere nota degli eventuali errori sotto elencati e riportarli sul forum di supporto tecnico.<br><br><b>La procedura di installazione è stata interrotta.</b>";
$error['locked']="Php-Stats sembra già essere installato e la procedura di installazione verrà terminata.<br><br>Se si vuole reinstallare Php-Stats cancellare prima il file <b>php-stats.lock</b>";
$error['error_config']="Php-Stats non è riuscito a creare il file di config, la procedura di installazione verrà terminata.<br><br>Se si vuole reinstallare Php-Stats cancellare prima il file <b>php-stats.lock</b>";
$error['nowrite_server']="<b>ATTENZIONE:</b> Non è possibile scrivere files sul tuo server.<br>Setta i permessi 777 alla cartella option<br>altrimenti se decidi di continuare verrà usata la modalità senza supporto di scrittura via WEB<br>";
?>